#! /bin/sh

picom &

sxhkd &

xsetroot -cursor_name left_ptr &

xset s off -dpms

sudo rmmod pcspkr &

numlockx on

autorandr -c --force

sorted=$(xrandr -q | grep '\bconnected' | sed 's/primary//' | awk '{print $3}' | sed 's/.*+\(.*\)+.*/\1/' | sort)
num=$(xrandr --query | grep -c '\bconnected')
if [ "$num" -eq "4" ]; then
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '1p')"+ | awk '{print $1}')" -d 1 2 3
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '2p')"+ | awk '{print $1}')" -d 4 5 6
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '1p')"+ | awk '{print $1}')" -d 7 8 9
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '1p')"+ | awk '{print $1}')" -d 10 11 12
elif [ "$num" -eq "3" ]; then
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '1p')"+ | awk '{print $1}')" -d 1 2 3 4
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '2p')"+ | awk '{print $1}')" -d 5 6 7 8
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '3p')"+ | awk '{print $1}')" -d 9 10 11 12
elif [ "$num" -eq "2" ]; then
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '1p')"+ | awk '{print $1}')" -d 1 2 3 4 5 6
    bspc monitor "$(xrandr -q | grep '\bconnected' | grep +"$(echo "$sorted" | sed -n '2p')"+ | awk '{print $1}')" -d 7 8 9 10 11 12
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12
fi

~/.config/polybar/run.sh &

~/.fehbg &

dunst --config ~/.config/dunst/dunstrc &

~/.config/bspwm/lockscreen &

~/.config/bspwm/bspwm_workspaces.sh &

# window gaps and width
bspc config border_width 0
bspc config window_gap 12

# window splitting rule
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
