#!/bin/bash

#rofi -modi run,drun -show drun -line-padding 4 -columns 2 -width 40 -padding 30 -hide-scrollbar -show-icons -drun-icon-theme "Papirus" -fuzzy
j4-dmenu-desktop --dmenu="dmenu -i -nb '#08090c' -nf '#f6f6f6' -sb '#3e4451' -sf '#f6f6f6' -l 10 -p 'Application'"
