#!/bin/bash
# shellcheck disable=SC2001
echo ""

playerctl metadata -F 2>&1 | while read -r line; do
    if [[ $line == *artist* ]]; then
        artist=$(sed 's/^.*:artist\s*\(.*\)/\1/g' <<< "$line")
#        echo "$artist - $title"
    elif [[ $line == *title* ]]; then
        title=$(sed 's/^.*:title\s*\(.*\)/\1/g' <<< "$line")
#        echo "$artist - $title"
    elif [[ $line == "" ]]; then
        echo ""
    fi
    if [[ $artist == "" && $title == "" ]]; then
        echo ""
    elif [[ $artist == ** && $title == "" ]]; then
        echo $artist
    elif [[ $artist == "" && $title == ** ]]; then
        echo $title
    elif [[ $artist == ** && $title == ** ]]; then
        echo "$artist - $title"
    fi
done
