#!/bin/bash
pause=""
play=""

playerctl status -F 2>/dev/null | while read -r line; do
    if [[ $line == "Playing" ]]; then
        echo "$pause"
    elif [[ $line == "Paused" ]]; then
        echo "$play"
    else
        echo ""
    fi
done
