#! /bin/sh
# wm independent hotkeys
#
# terminal emulator
super + Return
	xterm

super + KP_Enter
	xterm

# program launcher
super + space
    j4-dmenu-desktop --dmenu="dmenu -i -nb '#08090c' -nf '#f6f6f6' -sb '#3e4451' -sf '#f6f6f6'"

alt + space
    ~/.config/polybar/scripts/launcher

# apps
super + shift + {b,e,m,v,t}
    {firefox,xterm -e ranger,xterm -e ncmpcpp,xterm -e vim,xterm -e rtorrent}

super + e
    dolphin

# displaythingy
XF86Display
    ~/.config/bspwm/bspwm_workspaces_worker.sh

# brightness keybindings
XF86MonBrightness{Up,Down}
    brightnessctl s 5%{+,-} && value=$(echo "scale=2;$(cat /sys/class/backlight/*/brightness) / $(cat /sys/class/backlight/*/max_brightness)" | bc | sed 's/\.//'); dunstify "Brightness: [$value%]" -h "string:hlcolor:#3e4451" -h "int:value:$value" -t 500 -r 2 -a "OSD"

# media keys
XF86Audio{Next,Prev,Play,Stop}
    playerctl {next,previous,play-pause,pause}

# volume
XF86AudioRaiseVolume
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.02+ && value=$(~/.config/sxhkd/audio_status.sh --volume); dunstify "Volume: [$value]" -h "string:hlcolor:#3e4451" -h int:value:$value -t 500 -r 1 -a "OSD"
XF86AudioLowerVolume
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.02- &&  value=$(~/.config/sxhkd/audio_status.sh --volume); dunstify "Volume: [$value]" -h "string:hlcolor:#3e4451" -h int:value:$value -t 500 -r 1 -a "OSD"
XF86AudioMute
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle &&  value=$(~/.config/sxhkd/audio_status.sh --volume); dunstify "Volume: [$value]" "$(~/.config/sxhkd/audio_status.sh --mute)" -t 500 -r 1 -a "OSD"

XF86AudioMicMute
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

ctrl + alt + v
    ~/.config/sxhkd/volume.sh

ctrl + alt + b
    ~/.config/sxhkd/brightness.sh

# screenshot keybindings
Print
    flameshot screen -p ~/Pictures/Screenshots/
ctrl + Print
    flameshot full -p ~/Pictures/Screenshots/

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# gaps
super + alt + g
    bspc config window_gap 0
super + shift + g
    bspc config window_gap 12

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,alt + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next && dunstify "Monocle toggled" -t 1000 -r 5

#
# state/flags
#

# set the window state
super + {t,alt + t,s,f}
	tiling={tiled,pseudo_tiled,floating,fullscreen} &&  bspc node -t $tiling && dunstify "Window $tiling" -t 1000 -r 5

# set the node flags
super + ctrl + {m,x,y,z,h}
	bspc node -g {marked,locked,sticky,private,hidden}

#
# focus/swap
#

#focus desktop
super + shift + KP_{Add,Subtract}
	bspc desktop -f {next,prev}

# focus desktop number
super + shift + F{1,2,3,4,5,6,7,8,9,10,11,12}
  bspc desktop -f {1,2,3,4,5,6,7,8,9,10,11,12}

# focus the node in the given direction
super + shift + KP_{4,2,8,6}
	bspc node -f {west,south,north,east}

# send focused node to next or previous desktop
super + ctrl + shift + KP_{Add,Subtract}
	bspc node -d {next,prev} --follow

# send focused node to desktop number
super + ctrl + shift + F{1,2,3,4,5,6,7,8,9,10,11,12}
  bspc node -d {1,2,3,4,5,6,7,8,9,10,11,12} --follow

# swap node in the given direction
super + ctrl + shift + KP_{4,2,8,6}
	bspc node -s {west,south,north,east} --follow

# switch focus to last node
alt + Tab
	bspc node -f last

ctrl + alt + r
  ~/.config/sxhkd/reset_focus.sh
#
# move/resize
#

# expand a window by moving one of its side outward
super + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + shift + {Left,Down,Up,Right}
	bspc node -z {left 20 0,bottom 0 -20,top 0 20,right -20 0}

# move a floating window
super + alt + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# lockscreen
alt + shift + x
	betterlockscreen -l

alt + shift + Escape
	systemctl poweroff

alt + shift + c
    ~/.config/polybar/scripts/powermenu

ctrl + shift + Escape
    xterm -e btop
