#! /bin/sh
# wm independent hotkeys
#
# terminal emulator
super + Return
	xterm

super + KP_Enter
	xterm

# program launcher
super + @space
    dmenu_run -nb '#08090c' -nf '#f6f6f6' -sb '#181a1f' -sf '#f6f6f6'       

# apps
super + shift + {b,e,m,v,t}
    {firefox-bin,xterm -e ranger,xterm -e ncmpcpp,xterm -e vim,xterm -e rtorrent}

super + e
	polo-gtk

# scripts
super + shift + r
    redshift_toggle
super + F1
    faint        
super + F2
    faint_light
super + F3
    iris
super + F4
    gruvbox

# brightness keybindings
XF86MonBrightness{Up,Down}
    xbacklight {-inc,-dec} 5

# media keys
XF86Audio{Next,Prev,Play,Stop}
    /home/user/.local/bin/sp {next,prev,play,pause}

# volume
XF86AudioRaiseVolume
    amixer -q sset 'Master' 2%+
XF86AudioLowerVolume
    amixer -q sset 'Master' 2%-
XF86AudioMute
    amixer -q sset Master toggle 

# screenshot keybindings
Print
    flameshot screen -p '/home/user/Pictures/Screenshots/'
ctrl + Print
    flameshot full -p '/home/user/Pictures/Screenshots/'

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# gaps
super + alt  + g
    bspc config window_gap 0
super + shift + g
    bspc config window_gap 12

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,alt + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + b
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,alt + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

#focus next desktop
super + shift + KP_Add
	bspc desktop -f next

#focus previous desktop
super + shift + KP_Subtract
	bspc desktop -f prev

# focus the node in the given direction
super + {_,shift + }{KP_4,KP_2,KP_8,KP_6}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + shift + {Left,Down,Up,Right}
	bspc node -z {left 20 0,bottom 0 -20,top 0 20,right -20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# lockscreen
alt + shift + x
	betterlockscreen -l dim
